apiVersion: apps/v1
kind: Deployment
metadata:
  name: land-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: demo-api
          image: localhost:5000/demo-api
          ports:
            - containerPort: 5000
          env:
            - name: land.datasource.readreplica.jdbc-url
              value: jdbc:postgresql://land-postgresql:5432/postgres
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
spec:
  selector:
    app: demo-api
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer